[package]
name = "lintel_nes"
version = "0.0.0"
authors = [
  "Ryan Leckey <leckey.ryan@gmail.com>"
]

[dependencies]
bitflags = "0.7"
strfmt = "0.1.x"
log = "0.3.x"
env_logger = "0.3.x"
sdl2 = "0.27.x"
